li = [{'name': 'A Light in the Attic', 'price': 51.77, 'rating': 3},
      {'name': 'Tipping the Velvet', 'price': 53.74, 'rating': 1}, {'name': 'Soumission', 'price': 50.1, 'rating': 1},
      {'name': 'Sharp Objects', 'price': 47.82, 'rating': 4},
      {'name': 'Sapiens: A Brief History of Humankind', 'price': 54.23, 'rating': 5},
      {'name': 'The Requiem Red', 'price': 22.65, 'rating': 1},
      {'name': 'The Dirty Little Secrets of Getting Your Dream Job', 'price': 33.34, 'rating': 4},
      {'name': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
       'price': 17.93, 'rating': 3},
      {'name': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
       'price': 22.6, 'rating': 4}, {'name': 'The Black Maria', 'price': 52.15, 'rating': 1},
      {'name': 'Starving Hearts (Triangular Trade Trilogy, #1)', 'price': 13.99, 'rating': 2},
      {'name': "Shakespeare's Sonnets", 'price': 20.66, 'rating': 4},
      {'name': 'Set Me Free', 'price': 17.46, 'rating': 5},
      {'name': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'price': 52.29, 'rating': 5},
      {'name': 'Rip it Up and Start Again', 'price': 35.02, 'rating': 5},
      {'name': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'price': 57.25,
       'rating': 3}, {'name': 'Olio', 'price': 23.88, 'rating': 1},
      {'name': 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'price': 37.59, 'rating': 1},
      {'name': 'Libertarianism for Beginners', 'price': 51.33, 'rating': 2},
      {'name': "It's Only the Himalayas", 'price': 45.17, 'rating': 2},
      {'name': 'In Her Wake', 'price': 12.84, 'rating': 1}, {'name': 'How Music Works', 'price': 37.32, 'rating': 2}, {
          'name': 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More',
          'price': 30.52, 'rating': 3}, {'name': 'Chase Me (Paris Nights #2)', 'price': 25.27, 'rating': 5},
      {'name': 'Black Dust', 'price': 34.53, 'rating': 5},
      {'name': 'Birdsong: A Story in Pictures', 'price': 54.64, 'rating': 3}, {
          'name': "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana",
          'price': 22.5, 'rating': 3}, {'name': 'Aladdin and His Wonderful Lamp', 'price': 53.13, 'rating': 3},
      {'name': 'Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 'price': 40.3, 'rating': 5},
      {'name': 'Wall and Piece', 'price': 44.18, 'rating': 4},
      {'name': 'The Four Agreements: A Practical Guide to Personal Freedom', 'price': 17.66, 'rating': 5},
      {'name': 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate', 'price': 31.05,
       'rating': 3}, {'name': 'The Elephant Tree', 'price': 23.82, 'rating': 5},
      {'name': 'The Bear and the Piano', 'price': 36.89, 'rating': 1},
      {'name': "Sophie's World", 'price': 15.94, 'rating': 5}, {'name': 'Penny Maybe', 'price': 33.29, 'rating': 3},
      {'name': 'Maude (1883-1993):She Grew Up with the country', 'price': 18.02, 'rating': 2},
      {'name': 'In a Dark, Dark Wood', 'price': 19.63, 'rating': 1},
      {'name': 'Behind Closed Doors', 'price': 52.22, 'rating': 4},
      {'name': "You can't bury them all: Poems", 'price': 33.63, 'rating': 2},
      {'name': 'Slow States of Collapse: Poems', 'price': 57.31, 'rating': 3},
      {'name': 'Reasons to Stay Alive', 'price': 26.41, 'rating': 2},
      {'name': 'Private Paris (Private #10)', 'price': 47.61, 'rating': 5},
      {'name': '#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 'price': 23.11, 'rating': 5},
      {'name': 'Without Borders (Wanderlove #1)', 'price': 45.07, 'rating': 2},
      {'name': 'When We Collided', 'price': 31.77, 'rating': 1},
      {'name': 'We Love You, Charlie Freeman', 'price': 50.27, 'rating': 5},
      {'name': 'Untitled Collection: Sabbath Poems 2014', 'price': 14.27, 'rating': 4}, {
          'name': 'Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness',
          'price': 44.18, 'rating': 4}, {'name': 'Unicorn Tracks', 'price': 18.78, 'rating': 3},
      {'name': 'Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink',
       'price': 25.52, 'rating': 1},
      {'name': 'Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)', 'price': 16.28, 'rating': 1},
      {'name': 'Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity', 'price': 31.12,
       'rating': 3}, {'name': 'This One Summer', 'price': 19.49, 'rating': 4},
      {'name': 'Thirst', 'price': 17.27, 'rating': 5},
      {'name': 'The Torch Is Passed: A Harding Family Story', 'price': 19.09, 'rating': 1},
      {'name': 'The Secret of Dreadwillow Carse', 'price': 56.13, 'rating': 1}, {
          'name': 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!',
          'price': 56.41, 'rating': 1}, {'name': 'The Past Never Ends', 'price': 56.5, 'rating': 4},
      {'name': 'The Natural History of Us (The Fine Art of Pretending #2)', 'price': 45.22, 'rating': 3},
      {'name': 'The Nameless City (The Nameless City #1)', 'price': 38.16, 'rating': 4},
      {'name': 'The Murder That Never Was (Forensic Instincts #5)', 'price': 54.11, 'rating': 3},
      {'name': "The Most Perfect Thing: Inside (and Outside) a Bird's Egg", 'price': 42.96, 'rating': 4}, {
          'name': 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy',
          'price': 23.89, 'rating': 4},
      {'name': 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing', 'price': 16.77,
       'rating': 3},
      {'name': 'The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 'price': 20.59,
       'rating': 5}, {'name': 'The Gutsy Girl: Escapades for Your Life of Epic Adventure', 'price': 37.13, 'rating': 1},
      {'name': 'The Electric Pencil: Drawings from Inside State Hospital No. 3', 'price': 56.06, 'rating': 1},
      {'name': 'The Death of Humanity: and the Case for Life', 'price': 58.11, 'rating': 4},
      {'name': 'The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life',
       'price': 49.05, 'rating': 3}, {'name': 'The Art Forger', 'price': 40.76, 'rating': 3},
      {'name': 'The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind', 'price': 19.73,
       'rating': 1},
      {'name': "The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 'price': 32.24, 'rating': 5},
      {'name': 'Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up', 'price': 41.83,
       'rating': 4}, {'name': 'Soul Reader', 'price': 39.58, 'rating': 2},
      {'name': 'Security', 'price': 39.25, 'rating': 2},
      {'name': 'Saga, Volume 6 (Saga (Collected Editions) #6)', 'price': 25.02, 'rating': 3},
      {'name': 'Saga, Volume 5 (Saga (Collected Editions) #5)', 'price': 51.04, 'rating': 2},
      {'name': 'Reskilling America: Learning to Labor in the Twenty-First Century', 'price': 19.83, 'rating': 2},
      {'name': 'Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)', 'price': 50.4, 'rating': 3},
      {'name': 'Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 'price': 13.61,
       'rating': 5}, {'name': 'Princess Between Worlds (Wide-Awake Princess #5)', 'price': 13.34, 'rating': 5},
      {'name': 'Pop Gun War, Volume 1: Gift', 'price': 18.97, 'rating': 1}, {
          'name': 'Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics',
          'price': 36.28, 'rating': 2}, {'name': 'Patience', 'price': 10.16, 'rating': 3},
      {'name': 'Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)', 'price': 15.44, 'rating': 4},
      {'name': 'orange: The Complete Collection 1 (orange: The Complete Collection #1)', 'price': 48.41, 'rating': 1},
      {'name': 'Online Marketing for Busy Authors: A Step-By-Step Guide', 'price': 46.35, 'rating': 1},
      {'name': 'On a Midnight Clear', 'price': 14.07, 'rating': 3},
      {'name': 'Obsidian (Lux #1)', 'price': 14.86, 'rating': 2},
      {'name': 'My Paris Kitchen: Recipes and Stories', 'price': 33.37, 'rating': 2},
      {'name': 'Masks and Shadows', 'price': 56.4, 'rating': 2},
      {'name': 'Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 'price': 14.02,
       'rating': 4},
      {'name': 'Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)', 'price': 46.91, 'rating': 2},
      {'name': 'Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)', 'price': 45.61, 'rating': 3},
      {'name': 'Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)', 'price': 19.92, 'rating': 2},
      {'name': 'Layered: Baking, Building, and Styling Spectacular Cakes', 'price': 40.11, 'rating': 1},
      {'name': 'Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 'price': 53.9, 'rating': 2},
      {'name': 'Join', 'price': 35.67, 'rating': 5},
      {'name': 'In the Country We Love: My Family Divided', 'price': 22.0, 'rating': 4},
      {'name': 'Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine', 'price': 57.36, 'rating': 5},
      {'name': 'I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)', 'price': 29.17,
       'rating': 2}, {'name': 'I am a Hero Omnibus Volume 1', 'price': 54.63, 'rating': 3},
      {'name': 'How to Be Miserable: 40 Strategies You Already Use', 'price': 46.03, 'rating': 1},
      {'name': 'Her Backup Boyfriend (The Sorensen Family #1)', 'price': 33.97, 'rating': 1},
      {'name': 'Giant Days, Vol. 2 (Giant Days #5-8)', 'price': 22.11, 'rating': 2},
      {'name': 'Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton', 'price': 29.69,
       'rating': 3}, {'name': 'First and First (Five Boroughs #3)', 'price': 15.97, 'rating': 4},
      {'name': 'Fifty Shades Darker (Fifty Shades #2)', 'price': 21.96, 'rating': 1},
      {'name': 'Everydata: The Misinformation Hidden in the Little Data You Consume Every Day', 'price': 54.35,
       'rating': 2},
      {'name': "Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master", 'price': 37.97,
       'rating': 2}, {'name': 'Danganronpa Volume 1', 'price': 51.99, 'rating': 4},
      {'name': 'Crown of Midnight (Throne of Glass #2)', 'price': 43.29, 'rating': 3},
      {'name': 'Codename Baboushka, Volume 1: The Conclave of Death', 'price': 36.72, 'rating': 4},
      {'name': 'Camp Midnight', 'price': 17.08, 'rating': 4},
      {'name': 'Call the Nurse: True Stories of a Country Nurse on a Scottish Isle', 'price': 29.14, 'rating': 5},
      {'name': 'Burning', 'price': 28.81, 'rating': 3}, {'name': 'Bossypants', 'price': 49.46, 'rating': 2},
      {'name': 'Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))', 'price': 37.92,
       'rating': 2},
      {'name': 'Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)', 'price': 28.09,
       'rating': 2},
      {'name': 'Algorithms to Live By: The Computer Science of Human Decisions', 'price': 30.81, 'rating': 1},
      {'name': 'A World of Flavor: Your Gluten Free Passport', 'price': 42.95, 'rating': 1},
      {'name': 'A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations', 'price': 56.76, 'rating': 5},
      {'name': 'A Murder in Time', 'price': 16.64, 'rating': 1},
      {'name': 'A Flight of Arrows (The Pathfinders #2)', 'price': 55.53, 'rating': 5},
      {'name': 'A Fierce and Subtle Poison', 'price': 28.13, 'rating': 4},
      {'name': 'A Court of Thorns and Roses (A Court of Thorns and Roses #1)', 'price': 52.37, 'rating': 1},
      {'name': '(Un)Qualified: How God Uses Broken People to Do Big Things', 'price': 54.0, 'rating': 5},
      {'name': 'You Are What You Love: The Spiritual Power of Habit', 'price': 21.87, 'rating': 4},
      {'name': "William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)",
       'price': 43.3, 'rating': 4}, {'name': 'Tuesday Nights in 1980', 'price': 21.04, 'rating': 2},
      {'name': 'Tracing Numbers on a Train', 'price': 41.6, 'rating': 3},
      {'name': 'Throne of Glass (Throne of Glass #1)', 'price': 35.07, 'rating': 3},
      {'name': 'Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History',
       'price': 59.64, 'rating': 1}, {'name': 'Thirteen Reasons Why', 'price': 52.72, 'rating': 1},
      {'name': 'The White Cat and the Monk: A Retelling of the Poem â\x80\x9cPangur BÃ¡nâ\x80\x9d', 'price': 58.08,
       'rating': 4}, {'name': 'The Wedding Dress', 'price': 24.12, 'rating': 1},
      {'name': 'The Vacationers', 'price': 42.15, 'rating': 4},
      {'name': 'The Third Wave: An Entrepreneurâ\x80\x99s Vision of the Future', 'price': 12.61, 'rating': 5},
      {'name': 'The Stranger', 'price': 17.44, 'rating': 4},
      {'name': 'The Shadow Hero (The Shadow Hero)', 'price': 33.14, 'rating': 1},
      {'name': 'The Secret (The Secret #1)', 'price': 27.37, 'rating': 4},
      {'name': 'The Regional Office Is Under Attack!', 'price': 51.36, 'rating': 5},
      {'name': 'The Psychopath Test: A Journey Through the Madness Industry', 'price': 36.0, 'rating': 2},
      {'name': 'The Project', 'price': 10.65, 'rating': 1},
      {'name': 'The Power of Now: A Guide to Spiritual Enlightenment', 'price': 43.54, 'rating': 2},
      {'name': "The Omnivore's Dilemma: A Natural History of Four Meals", 'price': 38.21, 'rating': 2},
      {'name': 'The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us', 'price': 37.34, 'rating': 5},
      {'name': 'The Murder of Roger Ackroyd (Hercule Poirot #4)', 'price': 44.1, 'rating': 4},
      {'name': 'The Mistake (Off-Campus #2)', 'price': 43.29, 'rating': 3},
      {'name': "The Matchmaker's Playbook (Wingmen Inc. #1)", 'price': 55.85, 'rating': 1},
      {'name': 'The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking', 'price': 37.6,
       'rating': 2},
      {'name': 'The Long Shadow of Small Ghosts: Murder and Memory in an American City', 'price': 10.97, 'rating': 1},
      {'name': 'The Kite Runner', 'price': 41.82, 'rating': 4},
      {'name': 'The House by the Lake', 'price': 36.95, 'rating': 1},
      {'name': 'The Glittering Court (The Glittering Court #1)', 'price': 44.28, 'rating': 1},
      {'name': 'The Girl on the Train', 'price': 55.02, 'rating': 2},
      {'name': 'The Genius of Birds', 'price': 17.24, 'rating': 1},
      {'name': 'The Emerald Mystery', 'price': 23.15, 'rating': 2},
      {'name': 'The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First',
       'price': 41.25, 'rating': 1},
      {'name': "The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.",
       'price': 32.0, 'rating': 3},
      {'name': "The Artist's Way: A Spiritual Path to Higher Creativity", 'price': 38.49, 'rating': 5},
      {'name': 'The Art of War', 'price': 33.34, 'rating': 5}, {'name': 'The Argonauts', 'price': 10.93, 'rating': 2},
      {'name': 'The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job', 'price': 27.55,
       'rating': 3}, {'name': 'Suddenly in Love (Lake Haven #1)', 'price': 55.99, 'rating': 2},
      {'name': 'Something More Than This', 'price': 16.24, 'rating': 4},
      {'name': 'Soft Apocalypse', 'price': 26.12, 'rating': 2},
      {'name': "So You've Been Publicly Shamed", 'price': 12.23, 'rating': 2},
      {'name': 'Shoe Dog: A Memoir by the Creator of NIKE', 'price': 23.99, 'rating': 2},
      {'name': 'Shobu Samurai, Project Aryoku (#3)', 'price': 29.06, 'rating': 3},
      {'name': 'Secrets and Lace (Fatal Hearts #1)', 'price': 20.27, 'rating': 1},
      {'name': 'Scarlett Epstein Hates It Here', 'price': 43.55, 'rating': 5},
      {'name': 'Romero and Juliet: A Tragic Tale of Love and Zombies', 'price': 36.94, 'rating': 1},
      {'name': 'Redeeming Love', 'price': 20.47, 'rating': 5}, {
          'name': 'Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form',
          'price': 41.06, 'rating': 1}, {'name': 'Poems That Make Grown Women Cry', 'price': 14.19, 'rating': 4},
      {'name': 'Nightingale, Sing', 'price': 38.28, 'rating': 1},
      {'name': 'Night Sky with Exit Wounds', 'price': 41.05, 'rating': 1},
      {'name': 'Mrs. Houdini', 'price': 30.25, 'rating': 5}, {'name': 'Modern Romance', 'price': 28.26, 'rating': 5},
      {'name': 'Miss Peregrineâ\x80\x99s Home for Peculiar Children (Miss Peregrineâ\x80\x99s Peculiar Children #1)',
       'price': 10.76, 'rating': 1},
      {'name': 'Louisa: The Extraordinary Life of Mrs. Adams', 'price': 16.85, 'rating': 2},
      {'name': 'Little Red', 'price': 13.47, 'rating': 3},
      {'name': 'Library of Souls (Miss Peregrineâ\x80\x99s Peculiar Children #3)', 'price': 48.56, 'rating': 5},
      {'name': 'Large Print Heart of the Pride', 'price': 19.15, 'rating': 2},
      {'name': 'I Had a Nice Time And Other Lies...: How to find love & sh*t like that', 'price': 57.36, 'rating': 4},
      {'name': 'Hollow City (Miss Peregrineâ\x80\x99s Peculiar Children #2)', 'price': 42.98, 'rating': 1},
      {'name': 'Grumbles', 'price': 22.16, 'rating': 2},
      {'name': 'Full Moon over Noahâ\x80\x99s Ark: An Odyssey to Mount Ararat and Beyond', 'price': 49.43, 'rating': 4},
      {'name': 'Frostbite (Vampire Academy #2)', 'price': 29.99, 'rating': 5},
      {'name': 'Follow You Home', 'price': 21.36, 'rating': 1},
      {'name': 'First Steps for New Christians (Print Edition)', 'price': 29.0, 'rating': 1},
      {'name': 'Finders Keepers (Bill Hodges Trilogy #2)', 'price': 53.53, 'rating': 5},
      {'name': 'Fables, Vol. 1: Legends in Exile (Fables #1)', 'price': 41.62, 'rating': 4},
      {'name': 'Eureka Trivia 6.0', 'price': 54.59, 'rating': 4},
      {'name': 'Drive: The Surprising Truth About What Motivates Us', 'price': 34.95, 'rating': 4},
      {'name': 'Done Rubbed Out (Reightman & Bailey #1)', 'price': 37.72, 'rating': 5},
      {'name': 'Doing It Over (Most Likely To #1)', 'price': 35.61, 'rating': 3}, {
          'name': 'Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals',
          'price': 42.16, 'rating': 3}, {'name': 'Dark Notes', 'price': 19.19, 'rating': 5},
      {'name': 'Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead',
       'price': 19.43, 'rating': 3}, {'name': 'Close to You', 'price': 49.46, 'rating': 4},
      {'name': 'Chasing Heaven: What Dying Taught Me About Living', 'price': 37.8, 'rating': 2},
      {'name': 'Big Magic: Creative Living Beyond Fear', 'price': 30.8, 'rating': 3},
      {'name': 'Becoming Wise: An Inquiry into the Mystery and Art of Living', 'price': 27.43, 'rating': 2},
      {'name': 'Beauty Restored (Riley Family Legacy Novellas #3)', 'price': 11.11, 'rating': 2},
      {'name': 'Batman: The Long Halloween (Batman)', 'price': 36.5, 'rating': 2},
      {'name': 'Batman: The Dark Knight Returns (Batman)', 'price': 15.38, 'rating': 5},
      {'name': "Ayumi's Violin", 'price': 15.48, 'rating': 2}, {'name': 'Anonymous', 'price': 46.82, 'rating': 4},
      {'name': 'Amy Meets the Saints and Sages', 'price': 18.46, 'rating': 3},
      {'name': 'Amid the Chaos', 'price': 36.58, 'rating': 1}, {'name': 'Amatus', 'price': 50.54, 'rating': 5},
      {'name': 'Agnostic: A Spirited Manifesto', 'price': 12.51, 'rating': 5},
      {'name': 'Zealot: The Life and Times of Jesus of Nazareth', 'price': 24.7, 'rating': 3},
      {'name': 'You (You #1)', 'price': 43.61, 'rating': 5},
      {'name': 'Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)', 'price': 37.34, 'rating': 4},
      {'name': 'Wild Swans', 'price': 14.36, 'rating': 2},
      {'name': 'Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond', 'price': 52.65,
       'rating': 4},
      {'name': 'Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity',
       'price': 38.2, 'rating': 4},
      {'name': "What's It Like in Space?: Stories from Astronauts Who've Been There", 'price': 19.6, 'rating': 2},
      {'name': 'We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)', 'price': 53.9, 'rating': 1},
      {'name': "Walt Disney's Alice in Wonderland", 'price': 12.96, 'rating': 5},
      {'name': 'V for Vendetta (V for Vendetta Complete)', 'price': 37.1, 'rating': 4},
      {'name': 'Until Friday Night (The Field Party #1)', 'price': 46.31, 'rating': 2},
      {'name': 'Unbroken: A World War II Story of Survival, Resilience, and Redemption', 'price': 45.95, 'rating': 2},
      {'name': 'Twenty Yawns', 'price': 22.08, 'rating': 2}, {'name': 'Through the Woods', 'price': 25.38, 'rating': 2},
      {'name': 'This Is Where It Ends', 'price': 27.12, 'rating': 2},
      {'name': 'The Year of Magical Thinking', 'price': 43.04, 'rating': 2},
      {'name': 'The Wright Brothers', 'price': 56.8, 'rating': 4},
      {'name': "The White Queen (The Cousins' War #1)", 'price': 25.91, 'rating': 5},
      {'name': "The Wedding Pact (The O'Malleys #2)", 'price': 32.61, 'rating': 3},
      {'name': 'The Time Keeper', 'price': 27.88, 'rating': 5},
      {'name': 'The Testament of Mary', 'price': 52.67, 'rating': 4},
      {'name': 'The Star-Touched Queen', 'price': 46.02, 'rating': 5},
      {'name': 'The Songs of the Gods', 'price': 44.48, 'rating': 5},
      {'name': 'The Song of Achilles', 'price': 37.4, 'rating': 5},
      {'name': 'The Rosie Project (Don Tillman #1)', 'price': 54.04, 'rating': 1},
      {'name': 'The Power of Habit: Why We Do What We Do in Life and Business', 'price': 16.88, 'rating': 3},
      {'name': 'The Marriage of Opposites', 'price': 28.08, 'rating': 4},
      {'name': 'The Lucifer Effect: Understanding How Good People Turn Evil', 'price': 10.4, 'rating': 1},
      {'name': 'The Long Haul (Diary of a Wimpy Kid #9)', 'price': 44.07, 'rating': 1},
      {'name': 'The Loney', 'price': 23.4, 'rating': 1},
      {'name': 'The Literature Book (Big Ideas Simply Explained)', 'price': 17.43, 'rating': 3},
      {'name': 'The Last Mile (Amos Decker #2)', 'price': 54.21, 'rating': 2},
      {'name': 'The Immortal Life of Henrietta Lacks', 'price': 40.67, 'rating': 2},
      {'name': 'The Hidden Oracle (The Trials of Apollo #1)', 'price': 52.26, 'rating': 2}, {
          'name': 'The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth',
          'price': 28.77, 'rating': 3}, {'name': 'The Guilty (Will Robie #4)', 'price': 13.82, 'rating': 2},
      {'name': 'The First Hostage (J.B. Collins #2)', 'price': 25.85, 'rating': 3},
      {'name': 'The Dovekeepers', 'price': 48.78, 'rating': 1},
      {'name': 'The Darkest Lie', 'price': 35.35, 'rating': 5},
      {'name': 'The Bane Chronicles (The Bane Chronicles #1-11)', 'price': 44.73, 'rating': 4}, {
          'name': 'The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâ\x80\x99s Most Precious Manuscripts',
          'price': 15.77, 'rating': 1}, {'name': 'The 14th Colony (Cotton Malone #11)', 'price': 39.24, 'rating': 1},
      {'name': 'That Darkness (Gardiner and Renner #1)', 'price': 13.92, 'rating': 1},
      {'name': 'Tastes Like Fear (DI Marnie Rome #3)', 'price': 10.69, 'rating': 1},
      {'name': 'Take Me with You', 'price': 45.21, 'rating': 3},
      {'name': 'Swell: A Year of Waves', 'price': 45.58, 'rating': 1},
      {'name': 'Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)', 'price': 11.89, 'rating': 5},
      {'name': 'Still Life with Bread Crumbs', 'price': 26.41, 'rating': 3},
      {'name': 'Steve Jobs', 'price': 39.5, 'rating': 5},
      {'name': 'Sorting the Beef from the Bull: The Science of Food Fraud Forensics', 'price': 44.74, 'rating': 4},
      {'name': 'Someone Like You (The Harrisons #2)', 'price': 52.79, 'rating': 5},
      {'name': 'So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)', 'price': 35.43, 'rating': 4},
      {'name': 'Shtum', 'price': 55.84, 'rating': 4},
      {'name': 'See America: A Celebration of Our National Parks & Treasured Sites', 'price': 48.87, 'rating': 3},
      {'name': 'salt.', 'price': 46.78, 'rating': 4}, {'name': 'Robin War', 'price': 47.82, 'rating': 3},
      {'name': 'Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)', 'price': 25.48, 'rating': 2},
      {'name': 'Rain Fish', 'price': 23.57, 'rating': 3},
      {'name': 'Quarter Life Poetry: Poems for the Young, Broke and Hangry', 'price': 50.89, 'rating': 5},
      {'name': 'Pet Sematary', 'price': 10.56, 'rating': 3},
      {'name': 'Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress', 'price': 52.15,
       'rating': 3}, {'name': 'Once Was a Time', 'price': 18.28, 'rating': 2},
      {'name': 'Old School (Diary of a Wimpy Kid #10)', 'price': 11.83, 'rating': 5},
      {'name': 'No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon', 'price': 21.95, 'rating': 2},
      {'name': 'Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)', 'price': 38.39,
       'rating': 2}, {'name': 'My Name Is Lucy Barton', 'price': 41.56, 'rating': 1},
      {'name': 'My Mrs. Brown', 'price': 24.48, 'rating': 3}, {'name': 'My Kind of Crazy', 'price': 40.36, 'rating': 1},
      {'name': 'Mr. Mercedes (Bill Hodges Trilogy #1)', 'price': 28.9, 'rating': 1},
      {'name': 'More Than Music (Chasing the Dream #1)', 'price': 37.61, 'rating': 2},
      {'name': 'Made to Stick: Why Some Ideas Survive and Others Die', 'price': 38.85, 'rating': 5},
      {'name': 'Luis Paints the World', 'price': 53.95, 'rating': 3},
      {'name': 'Luckiest Girl Alive', 'price': 49.83, 'rating': 3},
      {'name': 'Lowriders to the Center of the Earth (Lowriders in Space #2)', 'price': 51.51, 'rating': 2},
      {'name': 'Love Is a Mix Tape (Music #1)', 'price': 18.03, 'rating': 1},
      {'name': 'Looking for Lovely: Collecting the Moments that Matter', 'price': 29.14, 'rating': 5},
      {'name': 'Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments', 'price': 46.91,
       'rating': 4}, {'name': 'Let It Out: A Journey Through Journaling', 'price': 26.79, 'rating': 5},
      {'name': 'Lady Midnight (The Dark Artifices #1)', 'price': 16.28, 'rating': 5},
      {'name': "It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes", 'price': 19.55, 'rating': 1},
      {'name': 'Island of Dragons (Unwanteds #7)', 'price': 29.65, 'rating': 1},
      {'name': "I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction",
       'price': 25.98, 'rating': 4}, {'name': 'I Am Pilgrim (Pilgrim #1)', 'price': 10.6, 'rating': 4}, {
          'name': 'Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened',
          'price': 14.75, 'rating': 5}, {'name': 'Hush, Hush (Hush, Hush #1)', 'price': 47.02, 'rating': 3},
      {'name': 'Hold Your Breath (Search and Rescue #1)', 'price': 28.82, 'rating': 1},
      {'name': 'Hamilton: The Revolution', 'price': 58.79, 'rating': 3},
      {'name': 'Greek Mythic History', 'price': 10.23, 'rating': 5},
      {'name': 'God: The Most Unpleasant Character in All Fiction', 'price': 30.03, 'rating': 5},
      {'name': 'Glory over Everything: Beyond The Kitchen House', 'price': 45.84, 'rating': 3},
      {'name': 'Feathers: Displays of Brilliant Plumage', 'price': 49.05, 'rating': 3},
      {'name': 'Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years', 'price': 15.06,
       'rating': 4}, {'name': 'Every Last Word', 'price': 46.47, 'rating': 3},
      {'name': 'Eligible (The Austen Project #4)', 'price': 27.09, 'rating': 3},
      {'name': 'El Deafo', 'price': 57.62, 'rating': 5}, {'name': 'Eight Hundred Grapes', 'price': 14.39, 'rating': 4},
      {'name': 'Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life',
       'price': 51.75, 'rating': 5}, {'name': 'Eat Fat, Get Thin', 'price': 54.07, 'rating': 2},
      {'name': "Don't Get Caught", 'price': 55.35, 'rating': 1},
      {'name': 'Doctor Sleep (The Shining #2)', 'price': 40.12, 'rating': 2}, {
          'name': 'Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)',
          'price': 37.51, 'rating': 5}, {'name': 'Dear Mr. Knightley', 'price': 11.21, 'rating': 5},
      {'name': 'Daily Fantasy Sports', 'price': 36.58, 'rating': 1},
      {'name': 'Crazy Love: Overwhelmed by a Relentless God', 'price': 47.72, 'rating': 2},
      {'name': 'Cometh the Hour (The Clifton Chronicles #6)', 'price': 25.01, 'rating': 3},
      {'name': 'Code Name Verity (Code Name Verity #1)', 'price': 22.13, 'rating': 4},
      {'name': 'Clockwork Angel (The Infernal Devices #1)', 'price': 44.14, 'rating': 1},
      {'name': 'City of Glass (The Mortal Instruments #3)', 'price': 56.02, 'rating': 4},
      {'name': 'City of Fallen Angels (The Mortal Instruments #4)', 'price': 11.23, 'rating': 4},
      {'name': 'City of Bones (The Mortal Instruments #1)', 'price': 43.28, 'rating': 1},
      {'name': 'City of Ashes (The Mortal Instruments #2)', 'price': 47.27, 'rating': 1},
      {'name': 'Cell', 'price': 20.29, 'rating': 4},
      {'name': 'Catching Jordan (Hundred Oaks)', 'price': 50.83, 'rating': 3},
      {'name': 'Carry On, Warrior: Thoughts on Life Unarmed', 'price': 31.85, 'rating': 3},
      {'name': 'Carrie', 'price': 46.23, 'rating': 2},
      {'name': 'Buying In: The Secret Dialogue Between What We Buy and Who We Are', 'price': 37.8, 'rating': 4},
      {'name': 'Brain on Fire: My Month of Madness', 'price': 49.32, 'rating': 5},
      {'name': 'Batman: Europa', 'price': 32.01, 'rating': 2},
      {'name': 'Barefoot Contessa Back to Basics', 'price': 28.01, 'rating': 1},
      {'name': "Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again", 'price': 50.62,
       'rating': 5}, {'name': 'Balloon Animals', 'price': 17.03, 'rating': 3},
      {'name': 'Art Ops Vol. 1', 'price': 48.8, 'rating': 3}, {
          'name': 'Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)',
          'price': 58.14, 'rating': 4}, {'name': 'Angels Walking (Angels Walking #1)', 'price': 34.2, 'rating': 2},
      {'name': 'Angels & Demons (Robert Langdon #1)', 'price': 51.48, 'rating': 3},
      {'name': 'All the Light We Cannot See', 'price': 29.87, 'rating': 5},
      {'name': 'Adulthood Is a Myth: A "Sarah\'s Scribbles" Collection', 'price': 10.9, 'rating': 2},
      {'name': 'Abstract City', 'price': 56.37, 'rating': 5},
      {'name': 'A Time of Torment (Charlie Parker #14)', 'price': 48.35, 'rating': 5},
      {'name': 'A Study in Scarlet (Sherlock Holmes #1)', 'price': 16.73, 'rating': 2},
      {'name': 'A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer', 'price': 56.48,
       'rating': 2}, {'name': "A People's History of the United States", 'price': 40.79, 'rating': 2},
      {'name': 'A Man Called Ove', 'price': 39.72, 'rating': 1},
      {'name': 'A Distant Mirror: The Caluserous 14th Century', 'price': 14.58, 'rating': 3},
      {'name': 'A Brush of Wings (Angels Walking #3)', 'price': 55.51, 'rating': 1},
      {'name': '1491: New Revelations of the Americas Before Columbus', 'price': 21.8, 'rating': 3},
      {'name': 'The Three Searches, Meaning, and the Story', 'price': 13.33, 'rating': 3},
      {'name': 'Searching for Meaning in Gailana', 'price': 38.73, 'rating': 1},
      {'name': 'Rook', 'price': 37.86, 'rating': 4},
      {'name': 'My Kitchen Year: 136 Recipes That Saved My Life', 'price': 11.53, 'rating': 2},
      {'name': '13 Hours: The Inside Account of What Really Happened In Benghazi', 'price': 27.06, 'rating': 1},
      {'name': "Will You Won't You Want Me?", 'price': 13.86, 'rating': 3},
      {'name': 'Tipping Point for Planet Earth: How Close Are We to the Edge?', 'price': 37.55, 'rating': 1},
      {'name': 'The Star-Touched Queen', 'price': 32.3, 'rating': 5},
      {'name': 'The Silent Sister (Riley MacPherson #1)', 'price': 46.29, 'rating': 5},
      {'name': 'The Midnight Watch: A Novel of the Titanic and the Californian', 'price': 26.2, 'rating': 1},
      {'name': 'The Lonely City: Adventures in the Art of Being Alone', 'price': 33.26, 'rating': 2},
      {'name': 'The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore', 'price': 59.15,
       'rating': 4},
      {'name': 'The Golden Condom: And Other Essays on Love Lost and Found', 'price': 39.43, 'rating': 1},
      {'name': 'The Epidemic (The Program 0.6)', 'price': 14.44, 'rating': 5},
      {'name': 'The Dinner Party', 'price': 56.54, 'rating': 2},
      {'name': 'The Diary of a Young Girl', 'price': 59.9, 'rating': 3},
      {'name': 'The Children', 'price': 11.88, 'rating': 3},
      {'name': 'Stars Above (The Lunar Chronicles #4.5)', 'price': 48.05, 'rating': 2},
      {'name': 'Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas',
       'price': 21.21, 'rating': 3},
      {'name': 'Raspberry Pi Electronics Projects for the Evil Genius', 'price': 49.67, 'rating': 4},
      {'name': 'Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two', 'price': 43.14, 'rating': 1},
      {'name': 'Psycho: Sanitarium (Psycho #1.5)', 'price': 36.97, 'rating': 5},
      {'name': 'Poisonous (Max Revere Novels #3)', 'price': 26.8, 'rating': 3},
      {'name': 'One with You (Crossfire #5)', 'price': 15.71, 'rating': 4},
      {'name': 'No Love Allowed (Dodge Cove #1)', 'price': 54.65, 'rating': 4},
      {'name': 'Murder at the 42nd Street Library (Raymond Ambler #1)', 'price': 54.36, 'rating': 4},
      {'name': 'Most Wanted', 'price': 35.28, 'rating': 3},
      {'name': 'Love, Lies and Spies', 'price': 20.55, 'rating': 2},
      {'name': 'How to Speak Golf: An Illustrated Guide to Links Lingo', 'price': 58.32, 'rating': 5},
      {'name': 'Hide Away (Eve Duncan #20)', 'price': 11.84, 'rating': 1},
      {'name': 'Furiously Happy: A Funny Book About Horrible Things', 'price': 41.46, 'rating': 4},
      {'name': 'Everyday Italian: 125 Simple and Delicious Recipes', 'price': 20.1, 'rating': 5},
      {'name': "Equal Is Unfair: America's Misguided Fight Against Income Inequality", 'price': 56.86, 'rating': 1},
      {'name': 'Eleanor & Park', 'price': 56.51, 'rating': 5},
      {'name': 'Dirty (Dive Bar #1)', 'price': 40.83, 'rating': 4},
      {'name': 'Can You Keep a Secret? (Fear Street Relaunch #4)', 'price': 48.64, 'rating': 1},
      {'name': 'Boar Island (Anna Pigeon #19)', 'price': 59.48, 'rating': 3},
      {'name': 'A Paris Apartment', 'price': 39.01, 'rating': 4}, {
          'name': 'A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More',
          'price': 38.77, 'rating': 1},
      {'name': 'Troublemaker: Surviving Hollywood and Scientology', 'price': 48.39, 'rating': 2},
      {'name': 'The Widow', 'price': 27.26, 'rating': 2},
      {'name': 'The Sleep Revolution: Transforming Your Life, One Night at a Time', 'price': 11.68, 'rating': 4},
      {'name': 'The Improbability of Love', 'price': 59.45, 'rating': 1},
      {'name': 'The Art of Startup Fundraising', 'price': 21.0, 'rating': 3},
      {'name': 'Take Me Home Tonight (Rock Star Romance #3)', 'price': 53.98, 'rating': 3},
      {'name': 'Sleeping Giants (Themis Files #1)', 'price': 48.74, 'rating': 1},
      {'name': 'Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena', 'price': 21.15,
       'rating': 2}, {'name': 'Playing with Fire', 'price': 13.71, 'rating': 3},
      {'name': 'Off the Hook (Fishing for Trouble #1)', 'price': 47.67, 'rating': 3},
      {'name': 'Mothering Sunday', 'price': 13.34, 'rating': 2},
      {'name': 'Mother, Can You Not?', 'price': 16.89, 'rating': 5}, {'name': 'M Train', 'price': 27.18, 'rating': 1},
      {'name': 'Lilac Girls', 'price': 17.28, 'rating': 2},
      {'name': 'Lies and Other Acts of Love', 'price': 45.14, 'rating': 1},
      {'name': 'Lab Girl', 'price': 40.85, 'rating': 1}, {'name': 'Keep Me Posted', 'price': 20.46, 'rating': 4},
      {'name': "It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle",
       'price': 56.27, 'rating': 3}, {'name': 'Grey (Fifty Shades #4)', 'price': 48.49, 'rating': 4},
      {'name': 'Exit, Pursued by a Bear', 'price': 51.34, 'rating': 4},
      {'name': 'Daredevils', 'price': 16.34, 'rating': 3},
      {'name': 'Cravings: Recipes for What You Want to Eat', 'price': 20.5, 'rating': 3},
      {'name': 'Born for This: How to Find the Work You Were Meant to Do', 'price': 21.59, 'rating': 5},
      {'name': 'Arena', 'price': 21.36, 'rating': 4}, {'name': 'Adultery', 'price': 20.88, 'rating': 5},
      {'name': "A Mother's Reckoning: Living in the Aftermath of Tragedy", 'price': 19.53, 'rating': 3},
      {'name': "A Gentleman's Position (Society of Gentlemen #3)", 'price': 14.75, 'rating': 5},
      {'name': '11/22/63', 'price': 48.48, 'rating': 3}, {
          'name': '10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works',
          'price': 24.57, 'rating': 2},
      {'name': '10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!', 'price': 49.71, 'rating': 5},
      {'name': 'Without Shame', 'price': 48.27, 'rating': 5}, {'name': 'Watchmen', 'price': 58.05, 'rating': 4},
      {'name': 'Unlimited Intuition Now', 'price': 58.87, 'rating': 4},
      {'name': 'Underlying Notes', 'price': 11.82, 'rating': 2}, {'name': 'The Shack', 'price': 28.03, 'rating': 1},
      {'name': 'The New Brand You: Your New Image Makes the Sale for You', 'price': 44.05, 'rating': 5},
      {'name': 'The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York', 'price': 12.34,
       'rating': 4}, {'name': 'The Flowers Lied', 'price': 16.68, 'rating': 2},
      {'name': 'The Fabric of the Cosmos: Space, Time, and the Texture of Reality', 'price': 55.91, 'rating': 1},
      {'name': 'The Book of Mormon', 'price': 24.57, 'rating': 3},
      {'name': 'The Art and Science of Low Carbohydrate Living', 'price': 52.98, 'rating': 5},
      {'name': 'The Alien Club', 'price': 54.4, 'rating': 1},
      {'name': 'Suzie Snowflake: One beautiful flake (a self-esteem story)', 'price': 54.81, 'rating': 5},
      {'name': 'Nap-a-Roo', 'price': 25.08, 'rating': 1}, {
          'name': 'NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond',
          'price': 10.41, 'rating': 4}, {'name': 'Modern Day Fables', 'price': 47.44, 'rating': 2},
      {'name': "If I Gave You God's Phone Number....: Searching for Spirituality in America", 'price': 20.91,
       'rating': 1}, {'name': 'Fruits Basket, Vol. 9 (Fruits Basket #9)', 'price': 33.95, 'rating': 4},
      {'name': 'Dress Your Family in Corduroy and Denim', 'price': 43.68, 'rating': 3},
      {'name': "Don't Forget Steven", 'price': 33.23, 'rating': 1},
      {'name': "Chernobyl 01:23:40: The Incredible True Story of the World's Worst Nuclear Disaster", 'price': 35.92,
       'rating': 2},
      {'name': 'Art and Fear: Observations on the Perils (and Rewards) of Artmaking', 'price': 48.63, 'rating': 4},
      {'name': 'A Shard of Ice (The Black Symphony Saga #1)', 'price': 56.63, 'rating': 3},
      {'name': "A Hero's Curse (The Unseen Chronicles #1)", 'price': 50.49, 'rating': 3},
      {'name': '23 Degrees South: A Tropical Tale of Changing Whether...', 'price': 35.79, 'rating': 2},
      {'name': 'Zero to One: Notes on Startups, or How to Build the Future', 'price': 34.06, 'rating': 3},
      {'name': 'Why Not Me?', 'price': 17.76, 'rating': 1},
      {'name': 'When Breath Becomes Air', 'price': 39.36, 'rating': 2},
      {'name': 'Vagabonding: An Uncommon Guide to the Art of Long-Term World Travel', 'price': 36.94, 'rating': 2},
      {'name': 'The Unlikely Pilgrimage of Harold Fry (Harold Fry #1)', 'price': 43.62, 'rating': 5},
      {'name': 'The New Drawing on the Right Side of the Brain', 'price': 43.02, 'rating': 3},
      {'name': "The Midnight Assassin: Panic, Scandal, and the Hunt for America's First Serial Killer", 'price': 28.45,
       'rating': 4}, {'name': 'The Martian (The Martian #1)', 'price': 41.39, 'rating': 2},
      {'name': 'The High Mountains of Portugal', 'price': 51.15, 'rating': 1},
      {'name': 'The Grownup', 'price': 35.88, 'rating': 1},
      {'name': "The E-Myth Revisited: Why Most Small Businesses Don't Work and What to Do About It", 'price': 36.91,
       'rating': 1}, {'name': 'South of Sunshine', 'price': 28.93, 'rating': 1},
      {'name': 'Smarter Faster Better: The Secrets of Being Productive in Life and Business', 'price': 38.89,
       'rating': 5}, {'name': 'Silence in the Dark (Logan Point #4)', 'price': 58.33, 'rating': 3},
      {'name': 'Shadows of the Past (Logan Point #1)', 'price': 39.67, 'rating': 5},
      {'name': 'Roller Girl', 'price': 14.1, 'rating': 5}, {'name': 'Rising Strong', 'price': 21.82, 'rating': 3},
      {'name': 'Proofs of God: Classical Arguments from Tertullian to Barth', 'price': 54.21, 'rating': 1},
      {'name': 'Please Kill Me: The Uncensored Oral History of Punk', 'price': 31.19, 'rating': 4},
      {'name': 'Out of Print: City Lights Spotlight No. 14', 'price': 53.64, 'rating': 5},
      {'name': 'My Life Next Door (My Life Next Door )', 'price': 36.39, 'rating': 5},
      {'name': "Miller's Valley", 'price': 58.54, 'rating': 2},
      {'name': "Man's Search for Meaning", 'price': 29.48, 'rating': 3}, {
          'name': "Love That Boy: What Two Presidents, Eight Road Trips, and My Son Taught Me About a Parent's Expectations",
          'price': 25.06, 'rating': 2},
      {'name': 'Living Forward: A Proven Plan to Stop Drifting and Get the Life You Want', 'price': 12.55, 'rating': 3},
      {'name': 'Les Fleurs du Mal', 'price': 29.04, 'rating': 5},
      {'name': 'Left Behind (Left Behind #1)', 'price': 40.72, 'rating': 2},
      {'name': "Kill 'Em and Leave: Searching for James Brown and the American Soul", 'price': 45.05, 'rating': 5},
      {'name': 'Kierkegaard: A Christian Missionary to Christians', 'price': 47.13, 'rating': 1},
      {'name': 'John Vassos: Industrial Design for Modern Life', 'price': 20.22, 'rating': 4},
      {'name': "I'll Give You the Sun", 'price': 56.48, 'rating': 1},
      {'name': 'I Will Find You', 'price': 44.21, 'rating': 1},
      {'name': 'Hystopia: A Novel', 'price': 21.96, 'rating': 4},
      {'name': 'Howl and Other Poems', 'price': 40.45, 'rating': 2},
      {'name': 'History of Beauty', 'price': 10.29, 'rating': 4},
      {'name': "Heaven is for Real: A Little Boy's Astounding Story of His Trip to Heaven and Back", 'price': 52.86,
       'rating': 2}, {'name': 'Future Shock (Future Shock #1)', 'price': 55.65, 'rating': 5},
      {'name': "Ender's Game (The Ender Quintet #1)", 'price': 43.64, 'rating': 1},
      {'name': 'Diary of a Citizen Scientist: Chasing Tiger Beetles and Other New Ways of Engaging the World',
       'price': 28.41, 'rating': 1}, {'name': 'Death by Leisure: A Cautionary Tale', 'price': 37.51, 'rating': 4},
      {'name': 'Brilliant Beacons: A History of the American Lighthouse', 'price': 11.45, 'rating': 3},
      {'name': "Brazen: The Courage to Find the You That's Been Hiding", 'price': 19.22, 'rating': 2},
      {'name': 'Between the World and Me', 'price': 56.91, 'rating': 4},
      {'name': 'Being Mortal: Medicine and What Matters in the End', 'price': 55.06, 'rating': 4},
      {'name': 'A Murder Over a Girl: Justice, Gender, Junior High', 'price': 13.2, 'rating': 3},
      {'name': '32 Yolks', 'price': 53.63, 'rating': 2},
      {'name': '"Most Blessed of the Patriarchs": Thomas Jefferson and the Empire of the Imagination', 'price': 44.48,
       'rating': 5},
      {'name': 'You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life', 'price': 12.08,
       'rating': 3}, {'name': 'Wildlife of New York: A Five-Borough Coloring Book', 'price': 22.14, 'rating': 2},
      {'name': 'What Happened on Beale Street (Secrets of the South Mysteries #2)', 'price': 25.37, 'rating': 5},
      {'name': 'Unreasonable Hope: Finding Faith in the God Who Brings Purpose to Your Pain', 'price': 46.33,
       'rating': 2}, {'name': 'Under the Tuscan Sun', 'price': 37.33, 'rating': 3},
      {'name': "Toddlers Are A**holes: It's Not Your Fault", 'price': 25.55, 'rating': 1},
      {'name': "The Year of Living Biblically: One Man's Humble Quest to Follow the Bible as Literally as Possible",
       'price': 34.72, 'rating': 1}, {'name': 'The Whale', 'price': 35.96, 'rating': 4},
      {'name': 'The Story of Art', 'price': 41.14, 'rating': 4},
      {'name': 'The Origin of Species', 'price': 10.01, 'rating': 4},
      {'name': 'The Great Gatsby', 'price': 36.05, 'rating': 4}, {'name': 'The Good Girl', 'price': 49.03, 'rating': 3},
      {'name': 'The Glass Castle', 'price': 16.24, 'rating': 1},
      {'name': "The Faith of Christopher Hitchens: The Restless Soul of the World's Most Notorious Atheist",
       'price': 39.55, 'rating': 1}, {'name': 'The Drowning Girls', 'price': 35.67, 'rating': 3},
      {'name': 'The Constant Princess (The Tudor Court #1)', 'price': 16.62, 'rating': 3},
      {'name': 'The Bourne Identity (Jason Bourne #1)', 'price': 42.78, 'rating': 4},
      {'name': "The Bachelor Girl's Guide to Murder (Herringford and Watts Mysteries #1)", 'price': 52.3, 'rating': 5},
      {'name': 'The Art Book', 'price': 32.34, 'rating': 2},
      {'name': 'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change', 'price': 33.17,
       'rating': 4}, {'name': 'Team of Rivals: The Political Genius of Abraham Lincoln', 'price': 20.12, 'rating': 5},
      {'name': 'Steal Like an Artist: 10 Things Nobody Told You About Being Creative', 'price': 20.9, 'rating': 2},
      {'name': 'Sit, Stay, Love', 'price': 20.9, 'rating': 3}, {'name': 'Sister Dear', 'price': 40.2, 'rating': 4},
      {'name': 'Shrunken Treasures: Literary Classics, Short, Sweet, and Silly', 'price': 52.87, 'rating': 3},
      {'name': 'Rich Dad, Poor Dad', 'price': 51.74, 'rating': 1},
      {'name': 'Raymie Nightingale', 'price': 34.41, 'rating': 2},
      {'name': 'Playing from the Heart', 'price': 32.38, 'rating': 1},
      {'name': 'Nightstruck: A Novel', 'price': 50.35, 'rating': 4},
      {'name': 'Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories',
       'price': 11.38, 'rating': 5}, {'name': 'Meternity', 'price': 43.58, 'rating': 3},
      {'name': 'Memoirs of a Geisha', 'price': 49.67, 'rating': 3},
      {'name': 'Like Never Before (Walker Family #2)', 'price': 28.77, 'rating': 2},
      {'name': 'Life of Pi', 'price': 13.22, 'rating': 4},
      {'name': 'Leave This Song Behind: Teen Poetry at Its Best', 'price': 51.17, 'rating': 5},
      {'name': "King's Folly (The Kinsman Chronicles #1)", 'price': 39.61, 'rating': 5},
      {'name': 'John Adams', 'price': 57.43, 'rating': 4},
      {'name': 'How to Cook Everything Vegetarian: Simple Meatless Recipes for Great Food (How to Cook Everything)',
       'price': 46.01, 'rating': 4},
      {'name': 'How to Be a Domestic Goddess: Baking and the Art of Comfort Cooking', 'price': 28.25, 'rating': 2},
      {'name': 'Good in Bed (Cannie Shapiro #1)', 'price': 37.05, 'rating': 5},
      {'name': 'Fruits Basket, Vol. 7 (Fruits Basket #7)', 'price': 19.57, 'rating': 1},
      {'name': 'For the Love: Fighting for Grace in a World of Impossible Standards', 'price': 45.13, 'rating': 3},
      {'name': 'Finding God in the Ruins: How God Redeems Pain', 'price': 46.64, 'rating': 2},
      {'name': 'Every Heart a Doorway (Every Heart A Doorway #1)', 'price': 12.16, 'rating': 5},
      {'name': 'Delivering the Truth (Quaker Midwife Mystery #1)', 'price': 20.89, 'rating': 4},
      {'name': 'Counted With the Stars (Out from Egypt #1)', 'price': 17.97, 'rating': 5},
      {'name': 'Chronicles, Vol. 1', 'price': 52.6, 'rating': 2},
      {'name': 'Blue Like Jazz: Nonreligious Thoughts on Christian Spirituality', 'price': 25.77, 'rating': 1},
      {'name': 'Benjamin Franklin: An American Life', 'price': 48.19, 'rating': 3}, {
          'name': 'At The Existentialist CafÃ©: Freedom, Being, and apricot cocktails with: Jean-Paul Sartre, Simone de Beauvoir, Albert Camus, Martin Heidegger, Edmund Husserl, Karl Jaspers, Maurice Merleau-Ponty and others',
          'price': 29.93, 'rating': 5}, {'name': 'A Summer In Europe', 'price': 44.34, 'rating': 2},
      {'name': 'A Short History of Nearly Everything', 'price': 52.4, 'rating': 5},
      {'name': 'A Gathering of Shadows (Shades of Magic #2)', 'price': 44.81, 'rating': 4},
      {'name': 'The Sound Of Love', 'price': 57.84, 'rating': 5},
      {'name': 'The Rise and Fall of the Third Reich: A History of Nazi Germany', 'price': 39.67, 'rating': 2},
      {'name': 'The Perks of Being a Wallflower', 'price': 55.02, 'rating': 3},
      {'name': 'The Mysterious Affair at Styles (Hercule Poirot #1)', 'price': 24.8, 'rating': 4},
      {'name': 'The Man Who Mistook His Wife for a Hat and Other Clinical Tales', 'price': 59.45, 'rating': 4},
      {'name': 'The Makings of a Fatherless Child', 'price': 31.58, 'rating': 2},
      {'name': 'The Joy of Cooking', 'price': 43.27, 'rating': 4},
      {'name': 'The Invention of Wings', 'price': 37.34, 'rating': 1},
      {'name': 'The Hobbit (Middle-Earth Universe)', 'price': 17.8, 'rating': 5},
      {'name': 'The Great Railway Bazaar', 'price': 30.54, 'rating': 1},
      {'name': 'The Golden Compass (His Dark Materials #1)', 'price': 18.77, 'rating': 1},
      {'name': 'The God Delusion', 'price': 46.85, 'rating': 3},
      {'name': 'The Girl You Left Behind (The Girl You Left Behind #1)', 'price': 15.79, 'rating': 1},
      {'name': 'The Fellowship of the Ring (The Lord of the Rings #1)', 'price': 10.27, 'rating': 2},
      {'name': 'The Collected Poems of W.B. Yeats (The Collected Works of W.B. Yeats #1)', 'price': 15.42, 'rating': 5},
      {'name': 'The Barefoot Contessa Cookbook', 'price': 59.92, 'rating': 5},
      {'name': "Tell the Wolves I'm Home", 'price': 50.96, 'rating': 2},
      {'name': 'Ship Leaves Harbor: Essays on Travel by a Recovering Journeyman', 'price': 30.6, 'rating': 3},
      {'name': 'Pride and Prejudice', 'price': 19.27, 'rating': 4},
      {'name': 'Musicophilia: Tales of Music and the Brain', 'price': 46.58, 'rating': 1},
      {'name': 'Mere Christianity', 'price': 48.51, 'rating': 3},
      {'name': 'Me Before You (Me Before You #1)', 'price': 19.02, 'rating': 1},
      {'name': 'In the Woods (Dublin Murder Squad #1)', 'price': 38.38, 'rating': 2},
      {'name': 'In Cold Blood', 'price': 49.98, 'rating': 4},
      {'name': 'How to Stop Worrying and Start Living', 'price': 46.49, 'rating': 5},
      {'name': 'Give It Back', 'price': 18.32, 'rating': 2}, {'name': 'Girl, Interrupted', 'price': 42.14, 'rating': 3},
      {'name': 'Fun Home: A Family Tragicomic', 'price': 56.59, 'rating': 4},
      {'name': 'Fruits Basket, Vol. 6 (Fruits Basket #6)', 'price': 20.96, 'rating': 4},
      {'name': 'Deception Point', 'price': 40.32, 'rating': 4},
      {'name': 'Death Note, Vol. 6: Give-and-Take (Death Note #6)', 'price': 36.39, 'rating': 3},
      {'name': 'Catherine the Great: Portrait of a Woman', 'price': 58.55, 'rating': 4},
      {'name': 'Better Homes and Gardens New Cook Book', 'price': 39.61, 'rating': 3},
      {'name': 'An Unquiet Mind: A Memoir of Moods and Madness', 'price': 21.3, 'rating': 3},
      {'name': 'A Year in Provence (Provence #1)', 'price': 56.88, 'rating': 4},
      {'name': 'World Without End (The Pillars of the Earth #2)', 'price': 32.97, 'rating': 4},
      {'name': 'Will Grayson, Will Grayson (Will Grayson, Will Grayson)', 'price': 47.31, 'rating': 4},
      {'name': 'Why Save the Bankers?: And Other Essays on Our Economic and Political Crisis', 'price': 48.67,
       'rating': 2}, {'name': 'Where She Went (If I Stay #2)', 'price': 41.73, 'rating': 4},
      {'name': 'What If?: Serious Scientific Answers to Absurd Hypothetical Questions', 'price': 53.68, 'rating': 4},
      {'name': 'Two Summers', 'price': 14.64, 'rating': 1},
      {'name': 'This Is Your Brain on Music: The Science of a Human Obsession', 'price': 38.4, 'rating': 1},
      {'name': 'The Secret Garden', 'price': 15.08, 'rating': 4},
      {'name': 'The Raven King (The Raven Cycle #4)', 'price': 30.57, 'rating': 2},
      {'name': 'The Raven Boys (The Raven Cycle #1)', 'price': 57.74, 'rating': 4},
      {'name': 'The Power Greens Cookbook: 140 Delicious Superfood Recipes', 'price': 11.05, 'rating': 5},
      {'name': 'The Metamorphosis', 'price': 28.58, 'rating': 1},
      {'name': "The Mathews Men: Seven Brothers and the War Against Hitler's U-boats", 'price': 42.91, 'rating': 5},
      {'name': 'The Little Paris Bookshop', 'price': 24.73, 'rating': 3},
      {'name': 'The Hiding Place', 'price': 55.91, 'rating': 4},
      {'name': 'The Grand Design', 'price': 13.76, 'rating': 3}, {'name': 'The Firm', 'price': 45.56, 'rating': 3},
      {'name': 'The Fault in Our Stars', 'price': 47.22, 'rating': 1},
      {'name': 'The False Prince (The Ascendance Trilogy #1)', 'price': 56.0, 'rating': 5},
      {'name': 'The Expatriates', 'price': 44.58, 'rating': 2},
      {'name': 'The Dream Thieves (The Raven Cycle #2)', 'price': 34.5, 'rating': 1},
      {'name': 'The Darkest Corners', 'price': 11.33, 'rating': 5},
      {'name': 'The Crossover', 'price': 38.77, 'rating': 4},
      {'name': 'The 5th Wave (The 5th Wave #1)', 'price': 11.83, 'rating': 2},
      {'name': 'Tell the Wind and Fire', 'price': 45.51, 'rating': 3},
      {'name': 'Tell Me Three Things', 'price': 41.81, 'rating': 1},
      {'name': "Talking to Girls About Duran Duran: One Young Man's Quest for True Love and a Cooler Haircut",
       'price': 25.15, 'rating': 4}, {'name': 'Siddhartha', 'price': 34.22, 'rating': 5},
      {'name': 'Shiver (The Wolves of Mercy Falls #1)', 'price': 16.23, 'rating': 5},
      {'name': 'Remember Me?', 'price': 11.48, 'rating': 3},
      {'name': 'Red Dragon (Hannibal Lecter #1)', 'price': 23.37, 'rating': 3},
      {'name': 'Peak: Secrets from the New Science of Expertise', 'price': 16.28, 'rating': 2},
      {'name': 'My Mother Was Nuts', 'price': 31.63, 'rating': 4},
      {'name': 'Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens', 'price': 24.91, 'rating': 5},
      {'name': 'Maybe Something Beautiful: How Art Transformed a Neighborhood', 'price': 22.54, 'rating': 1},
      {'name': 'Lola and the Boy Next Door (Anna and the French Kiss #2)', 'price': 23.63, 'rating': 4},
      {'name': 'Logan Kade (Fallen Crest High #5.5)', 'price': 13.12, 'rating': 2},
      {'name': 'Last One Home (New Beginnings #1)', 'price': 59.98, 'rating': 3},
      {'name': 'Killing Floor (Jack Reacher #1)', 'price': 31.49, 'rating': 4},
      {'name': 'Kill the Boy Band', 'price': 15.52, 'rating': 5},
      {'name': 'Isla and the Happily Ever After (Anna and the French Kiss #3)', 'price': 48.13, 'rating': 5},
      {'name': 'If I Stay (If I Stay #1)', 'price': 38.13, 'rating': 5},
      {'name': "I Know Why the Caged Bird Sings (Maya Angelou's Autobiography #1)", 'price': 36.55, 'rating': 2},
      {'name': 'Harry Potter and the Deathly Hallows (Harry Potter #7)', 'price': 23.32, 'rating': 1},
      {'name': 'Fruits Basket, Vol. 5 (Fruits Basket #5)', 'price': 16.33, 'rating': 1},
      {'name': 'Foundation (Foundation (Publication Order) #1)', 'price': 32.42, 'rating': 1},
      {'name': 'Fool Me Once', 'price': 16.96, 'rating': 1},
      {'name': 'Find Her (Detective D.D. Warren #8)', 'price': 22.37, 'rating': 1},
      {'name': 'Evicted: Poverty and Profit in the American City', 'price': 42.27, 'rating': 1},
      {'name': 'Drama', 'price': 38.7, 'rating': 2}, {'name': 'Dracula the Un-Dead', 'price': 35.63, 'rating': 5},
      {'name': 'Digital Fortress', 'price': 58.0, 'rating': 5},
      {'name': 'Death Note, Vol. 5: Whiteout (Death Note #5)', 'price': 52.41, 'rating': 1},
      {'name': 'Data, A Love Story: How I Gamed Online Dating to Meet My Match', 'price': 32.35, 'rating': 3},
      {'name': 'Critique of Pure Reason', 'price': 20.75, 'rating': 1}, {'name': 'Booked', 'price': 17.49, 'rating': 5},
      {'name': 'Blue Lily, Lily Blue (The Raven Cycle #3)', 'price': 34.13, 'rating': 5},
      {'name': 'Approval Junkie: Adventures in Caring Too Much', 'price': 58.81, 'rating': 5},
      {'name': 'An Abundance of Katherines', 'price': 10.0, 'rating': 5},
      {'name': "America's War for the Greater Middle East: A Military History", 'price': 51.22, 'rating': 2},
      {'name': 'Alight (The Generations Trilogy #2)', 'price': 58.59, 'rating': 4},
      {'name': "A Girl's Guide to Moving On (New Beginnings #2)", 'price': 31.3, 'rating': 1},
      {'name': 'A Game of Thrones (A Song of Ice and Fire #1)', 'price': 46.42, 'rating': 2},
      {'name': 'A Feast for Crows (A Song of Ice and Fire #4)', 'price': 17.21, 'rating': 4},
      {'name': 'A Clash of Kings (A Song of Ice and Fire #2)', 'price': 10.79, 'rating': 3},
      {'name': 'Vogue Colors A to Z: A Fashion Coloring Book', 'price': 52.35, 'rating': 4},
      {'name': 'The Shining (The Shining #1)', 'price': 27.88, 'rating': 3},
      {'name': "The Pilgrim's Progress", 'price': 50.26, 'rating': 2},
      {'name': 'The Perfect Play (Play by Play #1)', 'price': 59.99, 'rating': 3},
      {'name': 'The Passion of Dolssa', 'price': 28.32, 'rating': 5},
      {'name': 'The Jazz of Physics: The Secret Link Between Music and the Structure of the Universe', 'price': 38.71,
       'rating': 3}, {'name': 'The Hunger Games (The Hunger Games #1)', 'price': 29.85, 'rating': 5},
      {'name': 'The Hound of the Baskervilles (Sherlock Holmes #5)', 'price': 14.82, 'rating': 2},
      {'name': 'The Gunning of America: Business and the Making of American Gun Culture', 'price': 16.81, 'rating': 4},
      {'name': "The Geography of Bliss: One Grump's Search for the Happiest Places in the World", 'price': 28.23,
       'rating': 2}, {'name': 'The Demonists (Demonist #1)', 'price': 52.11, 'rating': 2},
      {'name': 'The Demon Prince of Momochi House, Vol. 4 (The Demon Prince of Momochi House #4)', 'price': 27.88,
       'rating': 2}, {'name': 'The Bone Hunters (Lexy Vaughan & Steven Macaulay #2)', 'price': 59.71, 'rating': 3},
      {'name': 'The Beast (Black Dagger Brotherhood #14)', 'price': 46.08, 'rating': 5},
      {'name': 'Some Women', 'price': 13.73, 'rating': 5},
      {'name': 'Shopaholic Ties the Knot (Shopaholic #3)', 'price': 48.39, 'rating': 5},
      {'name': 'Paper and Fire (The Great Library #2)', 'price': 49.45, 'rating': 5},
      {'name': 'Outlander (Outlander #1)', 'price': 19.67, 'rating': 5}, {
          'name': 'Orchestra of Exiles: The Story of Bronislaw Huberman, the Israel Philharmonic, and the One Thousand Jews He Saved from Nazi Horrors',
          'price': 12.36, 'rating': 3}, {'name': 'No One Here Gets Out Alive', 'price': 20.02, 'rating': 5},
      {'name': 'Night Shift (Night Shift #1-20)', 'price': 12.75, 'rating': 4},
      {'name': 'Needful Things', 'price': 47.51, 'rating': 4},
      {'name': 'Mockingjay (The Hunger Games #3)', 'price': 20.44, 'rating': 4},
      {'name': 'Misery', 'price': 34.79, 'rating': 2},
      {'name': 'Little Women (Little Women #1)', 'price': 28.07, 'rating': 4},
      {'name': 'It', 'price': 25.01, 'rating': 3},
      {'name': "Harry Potter and the Sorcerer's Stone (Harry Potter #1)", 'price': 13.9, 'rating': 3},
      {'name': 'Harry Potter and the Prisoner of Azkaban (Harry Potter #3)', 'price': 24.17, 'rating': 4},
      {'name': 'Harry Potter and the Order of the Phoenix (Harry Potter #5)', 'price': 31.63, 'rating': 4},
      {'name': 'Harry Potter and the Half-Blood Prince (Harry Potter #6)', 'price': 48.75, 'rating': 5},
      {'name': 'Harry Potter and the Chamber of Secrets (Harry Potter #2)', 'price': 14.74, 'rating': 1},
      {'name': 'Gone with the Wind', 'price': 32.49, 'rating': 3},
      {'name': 'God Is Not Great: How Religion Poisons Everything', 'price': 27.8, 'rating': 1},
      {'name': 'Girl With a Pearl Earring', 'price': 26.77, 'rating': 1},
      {'name': 'Fruits Basket, Vol. 4 (Fruits Basket #4)', 'price': 50.44, 'rating': 4},
      {'name': 'Far From True (Promise Falls Trilogy #2)', 'price': 34.93, 'rating': 2},
      {'name': 'Dark Lover (Black Dagger Brotherhood #1)', 'price': 12.87, 'rating': 1},
      {'name': 'Confessions of a Shopaholic (Shopaholic #1)', 'price': 48.94, 'rating': 2},
      {'name': 'Changing the Game (Play by Play #2)', 'price': 13.38, 'rating': 3},
      {'name': 'Candide', 'price': 58.63, 'rating': 3}, {'name': 'Can You Keep a Secret?', 'price': 21.94, 'rating': 1},
      {'name': 'Atlas Shrugged', 'price': 26.58, 'rating': 5}, {'name': 'Animal Farm', 'price': 57.22, 'rating': 3},
      {'name': 'A Walk to Remember', 'price': 56.43, 'rating': 1},
      {'name': "A New Earth: Awakening to Your Life's Purpose", 'price': 55.65, 'rating': 5},
      {'name': 'A History of God: The 4,000-Year Quest of Judaism, Christianity, and Islam', 'price': 27.62,
       'rating': 1}, {'name': "'Salem's Lot", 'price': 49.56, 'rating': 4},
      {'name': 'Zero History (Blue Ant #3)', 'price': 34.77, 'rating': 1},
      {'name': 'Wuthering Heights', 'price': 17.73, 'rating': 3},
      {'name': 'World War Z: An Oral History of the Zombie War', 'price': 21.8, 'rating': 1},
      {'name': 'Wild: From Lost to Found on the Pacific Crest Trail', 'price': 46.02, 'rating': 3},
      {'name': "Where'd You Go, Bernadette", 'price': 18.13, 'rating': 1},
      {'name': 'When You Are Engulfed in Flames', 'price': 30.89, 'rating': 5}, {
          'name': "We the People: The Modern-Day Figures Who Have Reshaped and Affirmed the Founding Fathers' Vision of America",
          'price': 31.95, 'rating': 3}, {'name': 'We Are All Completely Beside Ourselves', 'price': 24.04, 'rating': 1},
      {'name': 'Walk the Edge (Thunder Road #2)', 'price': 32.36, 'rating': 3},
      {'name': 'Voyager (Outlander #3)', 'price': 21.07, 'rating': 5},
      {'name': 'Very Good Lives: The Fringe Benefits of Failure and the Importance of Imagination', 'price': 50.66,
       'rating': 3},
      {'name': 'Vegan Vegetarian Omnivore: Dinner for Everyone at the Table', 'price': 13.66, 'rating': 2},
      {'name': 'Unstuffed: Decluttering Your Home, Mind, and Soul', 'price': 58.09, 'rating': 1},
      {'name': 'Under the Banner of Heaven: A Story of Violent Faith', 'price': 30.0, 'rating': 1},
      {'name': 'Two Boys Kissing', 'price': 32.74, 'rating': 2},
      {'name': 'Twilight (Twilight #1)', 'price': 41.93, 'rating': 2},
      {'name': 'Twenties Girl', 'price': 42.8, 'rating': 2}, {
          'name': "Trespassing Across America: One Man's Epic, Never-Done-Before (and Sort of Illegal) Hike Across the Heartland",
          'price': 53.51, 'rating': 1}, {'name': 'Three-Martini Lunch', 'price': 23.21, 'rating': 3},
      {'name': 'Thinking, Fast and Slow', 'price': 21.14, 'rating': 1},
      {'name': 'The Wild Robot', 'price': 56.07, 'rating': 3},
      {'name': 'The Wicked + The Divine, Vol. 3: Commercial Suicide (The Wicked + The Divine)', 'price': 14.41,
       'rating': 3}, {'name': 'The Undomestic Goddess', 'price': 45.75, 'rating': 4},
      {'name': 'The Travelers', 'price': 15.77, 'rating': 1},
      {'name': 'The Tipping Point: How Little Things Can Make a Big Difference', 'price': 10.02, 'rating': 2},
      {'name': 'The Thing About Jellyfish', 'price': 48.77, 'rating': 1},
      {'name': 'The Stand', 'price': 57.86, 'rating': 2},
      {'name': 'The Smitten Kitchen Cookbook', 'price': 23.59, 'rating': 1},
      {'name': 'The Silkworm (Cormoran Strike #2)', 'price': 23.05, 'rating': 5},
      {'name': 'The Sandman, Vol. 3: Dream Country (The Sandman (volumes) #3)', 'price': 55.55, 'rating': 5},
      {'name': 'The Rose & the Dagger (The Wrath and the Dawn #2)', 'price': 58.64, 'rating': 4},
      {'name': 'The Road to Little Dribbling: Adventures of an American in Britain (Notes From a Small Island #2)',
       'price': 23.21, 'rating': 1},
      {'name': 'The Rise of Theodore Roosevelt (Theodore Roosevelt #1)', 'price': 42.57, 'rating': 3},
      {'name': "The Restaurant at the End of the Universe (Hitchhiker's Guide to the Galaxy #2)", 'price': 10.92,
       'rating': 1}, {'name': 'The Rest Is Noise: Listening to the Twentieth Century', 'price': 34.77, 'rating': 1},
      {'name': 'The Red Tent', 'price': 35.66, 'rating': 5},
      {'name': 'The Purpose Driven Life: What on Earth Am I Here for?', 'price': 37.19, 'rating': 3},
      {'name': 'The Purest Hook (Second Circle Tattoos #3)', 'price': 12.25, 'rating': 1},
      {'name': 'The Picture of Dorian Gray', 'price': 29.7, 'rating': 2},
      {'name': 'The Paris Wife', 'price': 36.8, 'rating': 3}, {'name': 'The Obsession', 'price': 45.43, 'rating': 1},
      {'name': 'The Nightingale', 'price': 26.26, 'rating': 4},
      {'name': 'The New Guy (and Other Senior Year Distractions)', 'price': 44.92, 'rating': 3},
      {'name': 'The Nanny Diaries (Nanny #1)', 'price': 52.53, 'rating': 5},
      {'name': 'The Name of God is Mercy', 'price': 37.25, 'rating': 2},
      {'name': 'The Maze Runner (The Maze Runner #1)', 'price': 20.93, 'rating': 1},
      {'name': "The Lover's Dictionary", 'price': 58.09, 'rating': 2},
      {'name': 'The Lonely Ones', 'price': 43.59, 'rating': 5}, {
          'name': "The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
          'price': 33.92, 'rating': 3}, {'name': 'The Last Painting of Sara de Vos', 'price': 55.55, 'rating': 2},
      {'name': 'The Land of 10,000 Madonnas', 'price': 29.64, 'rating': 4},
      {'name': 'The Infinities', 'price': 27.41, 'rating': 1},
      {'name': "The Husband's Secret", 'price': 52.51, 'rating': 5},
      {'name': "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1)", 'price': 47.8,
       'rating': 3}, {'name': 'The Guns of August', 'price': 14.54, 'rating': 2},
      {'name': 'The Guernsey Literary and Potato Peel Pie Society', 'price': 49.53, 'rating': 1},
      {'name': 'The Goldfinch', 'price': 43.58, 'rating': 3},
      {'name': 'The Giver (The Giver Quartet #1)', 'price': 12.3, 'rating': 1},
      {'name': 'The Girl with All the Gifts', 'price': 49.47, 'rating': 3},
      {'name': 'The Girl Who Played with Fire (Millennium Trilogy #2)', 'price': 22.14, 'rating': 2},
      {'name': "The Girl Who Kicked the Hornet's Nest (Millennium Trilogy #3)", 'price': 57.48, 'rating': 1},
      {'name': 'The Exiled', 'price': 43.45, 'rating': 3},
      {'name': 'The End of Faith: Religion, Terror, and the Future of Reason', 'price': 22.13, 'rating': 4},
      {'name': 'The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory',
       'price': 13.03, 'rating': 4}, {
          'name': 'The Disappearing Spoon: And Other True Tales of Madness, Love, and the History of the World from the Periodic Table of the Elements',
          'price': 57.35, 'rating': 5},
      {'name': 'The Devil Wears Prada (The Devil Wears Prada #1)', 'price': 44.29, 'rating': 1},
      {'name': 'The Demon-Haunted World: Science as a Candle in the Dark', 'price': 52.25, 'rating': 4},
      {'name': 'The Day the Crayons Came Home (Crayons)', 'price': 26.33, 'rating': 5},
      {'name': 'The Da Vinci Code (Robert Langdon #2)', 'price': 22.96, 'rating': 2},
      {'name': "The Cuckoo's Calling (Cormoran Strike #1)", 'price': 19.21, 'rating': 1},
      {'name': 'The Complete Stories and Poems (The Works of Edgar Allan Poe [Cameo Edition])', 'price': 26.78,
       'rating': 4}, {'name': 'The Complete Poems', 'price': 41.32, 'rating': 5},
      {'name': 'The Catcher in the Rye', 'price': 24.55, 'rating': 1},
      {'name': 'The Cat in the Hat (Beginner Books B-1)', 'price': 16.26, 'rating': 2},
      {'name': 'The Case for Christ (Cases for Christianity)', 'price': 47.84, 'rating': 1},
      {'name': 'The Book Thief', 'price': 53.49, 'rating': 2},
      {'name': 'The Book of Basketball: The NBA According to The Sports Guy', 'price': 44.84, 'rating': 5},
      {'name': 'The Blind Side: Evolution of a Game', 'price': 53.71, 'rating': 5},
      {'name': 'The Autobiography of Malcolm X', 'price': 23.43, 'rating': 2},
      {'name': 'The Art of Simple Food: Notes, Lessons, and Recipes from a Delicious Revolution', 'price': 34.32,
       'rating': 3}, {'name': 'The Art of Fielding', 'price': 22.1, 'rating': 1},
      {'name': "Surely You're Joking, Mr. Feynman!: Adventures of a Curious Character", 'price': 25.83, 'rating': 2},
      {'name': 'Stiff: The Curious Lives of Human Cadavers', 'price': 36.74, 'rating': 3},
      {'name': 'Spilled Milk: Based on a True Story', 'price': 49.51, 'rating': 1},
      {'name': 'Something Borrowed (Darcy & Rachel #1)', 'price': 48.96, 'rating': 5},
      {'name': 'Something Blue (Darcy & Rachel #2)', 'price': 54.62, 'rating': 1},
      {'name': 'Soldier (Talon #3)', 'price': 24.72, 'rating': 2},
      {'name': 'Shopaholic & Baby (Shopaholic #5)', 'price': 46.45, 'rating': 2},
      {'name': 'Seven Days in the Art World', 'price': 52.33, 'rating': 2},
      {'name': 'Seven Brief Lessons on Physics', 'price': 30.6, 'rating': 4},
      {'name': 'Scarlet (The Lunar Chronicles #2)', 'price': 14.57, 'rating': 4},
      {'name': "Sarah's Key", 'price': 46.29, 'rating': 1},
      {'name': 'Saga, Volume 3 (Saga (Collected Editions) #3)', 'price': 21.57, 'rating': 5},
      {'name': 'Running with Scissors', 'price': 12.91, 'rating': 4},
      {'name': 'Rogue Lawyer (Rogue Lawyer #1)', 'price': 50.11, 'rating': 3},
      {'name': 'Rise of the Rocket Girls: The Women Who Propelled Us, from Missiles to the Moon to Mars',
       'price': 41.67, 'rating': 4}, {'name': 'Rework', 'price': 44.88, 'rating': 2},
      {'name': 'Reservations for Two', 'price': 11.1, 'rating': 3},
      {'name': 'Red: The True Story of Red Riding Hood', 'price': 28.54, 'rating': 3},
      {'name': 'Ready Player One', 'price': 19.07, 'rating': 4},
      {'name': "Quiet: The Power of Introverts in a World That Can't Stop Talking", 'price': 43.55, 'rating': 1},
      {'name': 'Prodigy: The Graphic Novel (Legend: The Graphic Novel #2)', 'price': 43.63, 'rating': 3},
      {'name': 'Persepolis: The Story of a Childhood (Persepolis #1-2)', 'price': 39.13, 'rating': 1},
      {'name': 'Packing for Mars: The Curious Science of Life in the Void', 'price': 56.68, 'rating': 2},
      {'name': 'Outliers: The Story of Success', 'price': 14.16, 'rating': 1},
      {'name': 'Original Fake', 'price': 31.45, 'rating': 3},
      {'name': 'Orange Is the New Black', 'price': 24.61, 'rating': 2},
      {'name': 'One for the Money (Stephanie Plum #1)', 'price': 32.87, 'rating': 2},
      {'name': 'Notes from a Small Island (Notes From a Small Island #1)', 'price': 40.17, 'rating': 1},
      {'name': 'Night (The Night Trilogy #1)', 'price': 13.51, 'rating': 1},
      {'name': 'Neither Here nor There: Travels in Europe', 'price': 38.95, 'rating': 3},
      {'name': 'Naked', 'price': 31.69, 'rating': 3},
      {'name': 'Morning Star (Red Rising #3)', 'price': 29.4, 'rating': 1},
      {'name': 'Miracles from Heaven: A Little Girl, Her Journey to Heaven, and Her Amazing Story of Healing',
       'price': 57.83, 'rating': 1},
      {'name': 'Midnight Riot (Peter Grant/ Rivers of London - books #1)', 'price': 55.46, 'rating': 2},
      {'name': 'Me Talk Pretty One Day', 'price': 57.6, 'rating': 2},
      {'name': 'Manuscript Found in Accra', 'price': 34.98, 'rating': 2},
      {'name': 'Lust & Wonder', 'price': 11.87, 'rating': 2}, {'name': 'Lila (Gilead #3)', 'price': 12.47, 'rating': 3},
      {'name': "Life, the Universe and Everything (Hitchhiker's Guide to the Galaxy #3)", 'price': 33.26, 'rating': 2},
      {'name': 'Life Without a Recipe', 'price': 59.04, 'rating': 5},
      {'name': 'Life After Life', 'price': 26.13, 'rating': 2},
      {'name': 'Letter to a Christian Nation', 'price': 22.2, 'rating': 1},
      {'name': "Let's Pretend This Never Happened: A Mostly True Memoir", 'price': 45.11, 'rating': 1},
      {'name': 'Legend (Legend #1)', 'price': 43.69, 'rating': 4},
      {'name': 'Lean In: Women, Work, and the Will to Lead', 'price': 25.02, 'rating': 1},
      {'name': "Lamb: The Gospel According to Biff, Christ's Childhood Pal", 'price': 55.5, 'rating': 5},
      {'name': 'Lady Renegades (Rebel Belle #3)', 'price': 53.04, 'rating': 5},
      {'name': 'Jurassic Park (Jurassic Park #1)', 'price': 44.97, 'rating': 1},
      {'name': "It's Never Too Late to Begin Again: Discovering Creativity and Meaning at Midlife and Beyond",
       'price': 42.38, 'rating': 1},
      {'name': 'Is Everyone Hanging Out Without Me? (And Other Concerns)', 'price': 20.11, 'rating': 3},
      {'name': 'Into the Wild', 'price': 56.7, 'rating': 5},
      {'name': 'Inferno (Robert Langdon #4)', 'price': 41.0, 'rating': 5},
      {'name': "In the Garden of Beasts: Love, Terror, and an American Family in Hitler's Berlin", 'price': 28.85,
       'rating': 3}, {'name': 'If I Run (If I Run #1)', 'price': 49.97, 'rating': 4},
      {'name': "I've Got Your Number", 'price': 19.69, 'rating': 1},
      {'name': 'I Am Malala: The Girl Who Stood Up for Education and Was Shot by the Taliban', 'price': 28.88,
       'rating': 2},
      {'name': 'Hungry Girl Clean & Hungry: Easy All-Natural Recipes for Healthy Eating in the Real World',
       'price': 33.14, 'rating': 3},
      {'name': 'House of Lost Worlds: Dinosaurs, Dynasties, and the Story of Life on Earth', 'price': 43.7,
       'rating': 2}, {'name': 'House of Leaves', 'price': 54.89, 'rating': 1},
      {'name': 'Horrible Bear!', 'price': 37.52, 'rating': 2}, {'name': 'Holidays on Ice', 'price': 51.07, 'rating': 2},
      {'name': 'Heir to the Sky', 'price': 44.07, 'rating': 4},
      {'name': 'Green Eggs and Ham (Beginner Books B-16)', 'price': 10.79, 'rating': 4},
      {'name': 'Grayson, Vol 3: Nemesis (Grayson #3)', 'price': 42.72, 'rating': 1},
      {'name': 'Gratitude', 'price': 26.66, 'rating': 5}, {'name': 'Gone Girl', 'price': 37.6, 'rating': 5},
      {'name': 'Golden (Heart of Dread #3)', 'price': 42.21, 'rating': 4},
      {'name': 'Girl in the Blue Coat', 'price': 46.83, 'rating': 2},
      {'name': 'Fruits Basket, Vol. 3 (Fruits Basket #3)', 'price': 45.17, 'rating': 2},
      {'name': 'Friday Night Lights: A Town, a Team, and a Dream', 'price': 51.22, 'rating': 3},
      {'name': 'Fire Bound (Sea Haven/Sisters of the Heart #5)', 'price': 21.28, 'rating': 4},
      {'name': 'Fifty Shades Freed (Fifty Shades #3)', 'price': 15.36, 'rating': 5},
      {'name': 'Fellside', 'price': 38.62, 'rating': 1},
      {'name': 'Extreme Prey (Lucas Davenport #26)', 'price': 25.4, 'rating': 3},
      {'name': 'Eragon (The Inheritance Cycle #1)', 'price': 43.87, 'rating': 3},
      {'name': 'Eclipse (Twilight #3)', 'price': 18.74, 'rating': 1},
      {'name': 'Dune (Dune #1)', 'price': 54.86, 'rating': 1}, {'name': 'Dracula', 'price': 52.62, 'rating': 3},
      {'name': 'Do Androids Dream of Electric Sheep? (Blade Runner #1)', 'price': 51.48, 'rating': 1},
      {'name': 'Disrupted: My Misadventure in the Start-Up Bubble', 'price': 15.28, 'rating': 5},
      {'name': 'Dead Wake: The Last Crossing of the Lusitania', 'price': 39.24, 'rating': 5},
      {'name': 'David and Goliath: Underdogs, Misfits, and the Art of Battling Giants', 'price': 17.81, 'rating': 1},
      {'name': 'Darkfever (Fever #1)', 'price': 56.02, 'rating': 1},
      {'name': 'Dark Places', 'price': 23.9, 'rating': 5},
      {'name': 'Crazy Rich Asians (Crazy Rich Asians #1)', 'price': 49.13, 'rating': 5},
      {'name': 'Counting Thyme', 'price': 10.62, 'rating': 1}, {'name': 'Cosmos', 'price': 36.17, 'rating': 2},
      {'name': 'Civilization and Its Discontents', 'price': 59.95, 'rating': 2},
      {'name': 'Cinder (The Lunar Chronicles #1)', 'price': 26.09, 'rating': 1},
      {'name': "Catastrophic Happiness: Finding Joy in Childhood's Messy Years", 'price': 37.35, 'rating': 2},
      {'name': 'Career of Evil (Cormoran Strike #3)', 'price': 24.72, 'rating': 2},
      {'name': 'Breaking Dawn (Twilight #4)', 'price': 35.28, 'rating': 5},
      {'name': 'Brave Enough', 'price': 51.32, 'rating': 5}, {'name': 'Boy Meets Boy', 'price': 21.12, 'rating': 3},
      {'name': 'Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen',
       'price': 27.35, 'rating': 2},
      {'name': 'Blink: The Power of Thinking Without Thinking', 'price': 21.74, 'rating': 5},
      {'name': 'Black Flags: The Rise of ISIS', 'price': 40.87, 'rating': 1},
      {'name': 'Black Butler, Vol. 1 (Black Butler #1)', 'price': 49.31, 'rating': 1},
      {'name': 'Big Little Lies', 'price': 22.11, 'rating': 1},
      {'name': 'Between Shades of Gray', 'price': 20.79, 'rating': 5},
      {'name': "Best of My Love (Fool's Gold #20)", 'price': 27.41, 'rating': 2},
      {'name': 'Beowulf', 'price': 38.35, 'rating': 2},
      {'name': 'Beautiful Creatures (Caster Chronicles #1)', 'price': 21.55, 'rating': 5},
      {'name': 'Awkward', 'price': 38.02, 'rating': 2}, {'name': 'Ash', 'price': 22.06, 'rating': 4},
      {'name': 'Are We There Yet?', 'price': 10.66, 'rating': 3},
      {'name': 'Are We Smart Enough to Know How Smart Animals Are?', 'price': 56.58, 'rating': 1},
      {'name': 'Annie on My Mind', 'price': 36.83, 'rating': 5},
      {'name': 'And Then There Were None', 'price': 35.01, 'rating': 2},
      {'name': 'A Walk in the Woods: Rediscovering America on the Appalachian Trail', 'price': 30.48, 'rating': 4},
      {'name': 'A Visit from the Goon Squad', 'price': 14.08, 'rating': 5},
      {'name': 'A Storm of Swords (A Song of Ice and Fire #3)', 'price': 31.22, 'rating': 2},
      {'name': 'A Heartbreaking Work of Staggering Genius', 'price': 54.29, 'rating': 5},
      {'name': '8 Keys to Mental Health Through Exercise', 'price': 31.04, 'rating': 1},
      {'name': '#GIRLBOSS', 'price': 50.96, 'rating': 1},
      {'name': 'The Suffragettes (Little Black Classics, #96)', 'price': 11.89, 'rating': 2},
      {'name': 'The Sense of an Ending', 'price': 31.38, 'rating': 3},
      {'name': "The Sandman, Vol. 2: The Doll's House (The Sandman (volumes) #2)", 'price': 54.81, 'rating': 1},
      {'name': 'The Course of Love', 'price': 16.78, 'rating': 3},
      {'name': 'Sugar Rush (Offensive Line #2)', 'price': 24.42, 'rating': 1},
      {'name': 'Saga, Volume 2 (Saga (Collected Editions) #2)', 'price': 11.75, 'rating': 3},
      {'name': 'Run, Spot, Run: The Ethics of Keeping Pets', 'price': 20.02, 'rating': 1},
      {'name': 'New Moon (Twilight #2)', 'price': 12.86, 'rating': 4}, {'name': 'Life', 'price': 31.58, 'rating': 5},
      {'name': "Kindle Paperwhite User's Guide", 'price': 34.0, 'rating': 3},
      {'name': 'H is for Hawk', 'price': 57.42, 'rating': 5},
      {'name': 'Girl Online On Tour (Girl Online #2)', 'price': 53.47, 'rating': 1},
      {'name': 'Fruits Basket, Vol. 2 (Fruits Basket #2)', 'price': 11.64, 'rating': 5},
      {'name': 'Diary of a Minecraft Zombie Book 1: A Scare of a Dare (An Unofficial Minecraft Book)', 'price': 52.88,
       'rating': 4}, {'name': 'Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)', 'price': 18.51, 'rating': 4},
      {'name': 'While You Were Mine', 'price': 41.32, 'rating': 5},
      {'name': 'Where Lightning Strikes (Bleeding Stars #3)', 'price': 39.77, 'rating': 3},
      {'name': "When I'm Gone", 'price': 51.96, 'rating': 3}, {'name': 'Ways of Seeing', 'price': 39.51, 'rating': 5},
      {'name': 'Vampire Knight, Vol. 1 (Vampire Knight #1)', 'price': 15.4, 'rating': 1},
      {'name': 'Vampire Girl (Vampire Girl #1)', 'price': 53.82, 'rating': 2},
      {'name': 'Twenty Love Poems and a Song of Despair', 'price': 30.95, 'rating': 4},
      {'name': 'Travels with Charley: In Search of America', 'price': 57.82, 'rating': 5},
      {'name': 'Three Wishes (River of Time: California #1)', 'price': 44.18, 'rating': 2},
      {'name': 'This One Moment (Pushing Limits #1)', 'price': 48.71, 'rating': 1},
      {'name': 'The Zombie Room', 'price': 19.69, 'rating': 5},
      {'name': 'The Wicked + The Divine, Vol. 1: The Faust Act (The Wicked + The Divine)', 'price': 36.52, 'rating': 2},
      {'name': 'The Tumor', 'price': 41.56, 'rating': 5},
      {'name': 'The Story of Hong Gildong', 'price': 43.19, 'rating': 4},
      {'name': 'The Silent Wife', 'price': 12.34, 'rating': 5},
      {'name': 'The Silent Twin (Detective Jennifer Knight #3)', 'price': 36.25, 'rating': 3},
      {'name': 'The Selfish Gene', 'price': 29.45, 'rating': 1},
      {'name': 'The Secret Healer', 'price': 34.56, 'rating': 3},
      {'name': 'The Sandman, Vol. 1: Preludes and Nocturnes (The Sandman (volumes) #1)', 'price': 54.12, 'rating': 3},
      {'name': 'The Republic', 'price': 33.78, 'rating': 3}, {'name': 'The Odyssey', 'price': 29.64, 'rating': 3},
      {'name': "The No. 1 Ladies' Detective Agency (No. 1 Ladies' Detective Agency #1)", 'price': 57.7, 'rating': 4},
      {'name': 'The Nicomachean Ethics', 'price': 36.34, 'rating': 1},
      {'name': 'The Name of the Wind (The Kingkiller Chronicle #1)', 'price': 50.59, 'rating': 3},
      {'name': 'The Mirror & the Maze (The Wrath and the Dawn #1.5)', 'price': 29.38, 'rating': 1},
      {'name': 'The Little Prince', 'price': 45.42, 'rating': 2},
      {'name': 'The Light of the Fireflies', 'price': 54.43, 'rating': 1},
      {'name': 'The Last Girl (The Dominion Trilogy #1)', 'price': 36.26, 'rating': 2},
      {'name': 'The Iliad', 'price': 16.16, 'rating': 1},
      {'name': 'The Hook Up (Game On #1)', 'price': 36.29, 'rating': 5},
      {'name': 'The Haters', 'price': 27.89, 'rating': 5}, {'name': 'The Girl You Lost', 'price': 12.29, 'rating': 5},
      {'name': 'The Girl In The Ice (DCI Erika Foster #1)', 'price': 15.85, 'rating': 3},
      {'name': 'The End of the Jesus Era (An Investigation #1)', 'price': 14.4, 'rating': 1},
      {'name': 'The Edge of Reason (Bridget Jones #2)', 'price': 19.18, 'rating': 4},
      {'name': 'The Complete Maus (Maus #1-2)', 'price': 10.64, 'rating': 3},
      {'name': 'The Communist Manifesto', 'price': 14.76, 'rating': 3},
      {'name': 'The Bhagavad Gita', 'price': 57.49, 'rating': 3},
      {'name': 'The Bette Davis Club', 'price': 30.66, 'rating': 3},
      {'name': 'The Art of Not Breathing', 'price': 40.83, 'rating': 4},
      {'name': 'Taking Shots (Assassins #1)', 'price': 18.88, 'rating': 2},
      {'name': 'Starlark', 'price': 25.83, 'rating': 3},
      {'name': 'Skip Beat!, Vol. 01 (Skip Beat! #1)', 'price': 42.12, 'rating': 3},
      {'name': 'Sister Sable (The Mad Queen #1)', 'price': 13.33, 'rating': 3},
      {'name': 'Shatter Me (Shatter Me #1)', 'price': 42.4, 'rating': 1},
      {'name': 'Shameless', 'price': 58.35, 'rating': 3},
      {'name': 'Shadow Rites (Jane Yellowrock #10)', 'price': 21.72, 'rating': 4},
      {'name': 'Settling the Score (The Summer Games #1)', 'price': 44.91, 'rating': 2},
      {'name': 'Sense and Sensibility', 'price': 37.46, 'rating': 1},
      {'name': 'Saga, Volume 1 (Saga (Collected Editions) #1)', 'price': 28.48, 'rating': 1},
      {'name': 'Rhythm, Chord & Malykhin', 'price': 28.34, 'rating': 2},
      {'name': 'Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collected Editions) #1-5)', 'price': 46.96,
       'rating': 5}, {'name': 'Paradise Lost (Paradise #1)', 'price': 24.96, 'rating': 1},
      {'name': 'Paper Girls, Vol. 1 (Paper Girls #1-5)', 'price': 21.71, 'rating': 4},
      {'name': 'Ouran High School Host Club, Vol. 1 (Ouran High School Host Club #1)', 'price': 29.87, 'rating': 3},
      {'name': 'Origins (Alphas 0.5)', 'price': 28.99, 'rating': 1},
      {'name': 'One Second (Seven #7)', 'price': 52.94, 'rating': 2},
      {'name': 'On the Road (Duluoz Legend)', 'price': 32.36, 'rating': 3},
      {'name': "Old Records Never Die: One Man's Quest for His Vinyl and His Past", 'price': 55.66, 'rating': 2},
      {'name': 'Off Sides (Off #1)', 'price': 39.45, 'rating': 5},
      {'name': 'Of Mice and Men', 'price': 47.11, 'rating': 2},
      {'name': 'Myriad (Prentor #1)', 'price': 58.75, 'rating': 4},
      {'name': 'My Perfect Mistake (Over the Top #1)', 'price': 38.92, 'rating': 2},
      {'name': 'Ms. Marvel, Vol. 1: No Normal (Ms. Marvel (2014-2015) #1)', 'price': 39.39, 'rating': 4},
      {'name': 'Meditations', 'price': 25.89, 'rating': 2}, {'name': 'Matilda', 'price': 28.34, 'rating': 1},
      {'name': 'Lost Among the Living', 'price': 27.7, 'rating': 4},
      {'name': 'Lord of the Flies', 'price': 24.89, 'rating': 3},
      {'name': 'Listen to Me (Fusion #1)', 'price': 58.99, 'rating': 3},
      {'name': 'Kitchens of the Great Midwest', 'price': 57.2, 'rating': 5},
      {'name': 'Jane Eyre', 'price': 38.43, 'rating': 5}, {'name': 'Imperfect Harmony', 'price': 34.74, 'rating': 4},
      {'name': 'Icing (Aces Hockey #2)', 'price': 40.44, 'rating': 4},
      {'name': 'Hawkeye, Vol. 1: My Life as a Weapon (Hawkeye #1)', 'price': 45.24, 'rating': 3},
      {'name': "Having the Barbarian's Baby (Ice Planet Barbarians #7.5)", 'price': 34.96, 'rating': 4},
      {'name': 'Giant Days, Vol. 1 (Giant Days #1-4)', 'price': 56.76, 'rating': 4},
      {'name': 'Fruits Basket, Vol. 1 (Fruits Basket #1)', 'price': 40.28, 'rating': 5},
      {'name': 'Frankenstein', 'price': 38.0, 'rating': 2},
      {'name': 'Forever Rockers (The Rocker #12)', 'price': 28.8, 'rating': 3},
      {'name': 'Fighting Fate (Fighting #6)', 'price': 39.24, 'rating': 3},
      {'name': 'Emma', 'price': 32.93, 'rating': 2}, {'name': 'Eat, Pray, Love', 'price': 51.32, 'rating': 3},
      {'name': 'Deep Under (Walker Security #1)', 'price': 47.09, 'rating': 5},
      {'name': "Choosing Our Religion: The Spiritual Lives of America's Nones", 'price': 28.42, 'rating': 4},
      {'name': 'Charlie and the Chocolate Factory (Charlie Bucket #1)', 'price': 22.85, 'rating': 3},
      {'name': "Charity's Cross (Charles Towne Belles #4)", 'price': 41.24, 'rating': 1},
      {'name': 'Bright Lines', 'price': 39.07, 'rating': 5},
      {'name': "Bridget Jones's Diary (Bridget Jones #1)", 'price': 29.82, 'rating': 1},
      {'name': 'Bounty (Colorado Mountain #7)', 'price': 37.26, 'rating': 4},
      {'name': 'Blood Defense (Samantha Brinkman #1)', 'price': 20.3, 'rating': 3},
      {'name': 'Bleach, Vol. 1: Strawberry and the Soul Reapers (Bleach #1)', 'price': 34.65, 'rating': 5},
      {'name': 'Beyond Good and Evil', 'price': 43.38, 'rating': 1},
      {'name': "Alice in Wonderland (Alice's Adventures in Wonderland #1)", 'price': 55.53, 'rating': 1},
      {'name': 'Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)', 'price': 57.06, 'rating': 4},
      {'name': "A Spy's Devotion (The Regency Spies of London #1)", 'price': 16.97, 'rating': 5},
      {'name': "1st to Die (Women's Murder Club #1)", 'price': 53.98, 'rating': 1},
      {'name': '1,000 Places to See Before You Die', 'price': 26.08, 'rating': 5}]
print ( len ( li ) )
